flags: {}
packages:
- '.'
extra-deps:
  - envparse-0.4.1@sha256:989902e6368532548f61de1fa245ad2b39176cddd8743b20071af519a709ce30,2842
  - yamlparse-applicative-0.1.0.2@sha256:bda91f2818c1b5b124963931cb7f9a4e5758d026c09713e9ae2234534062747d,2133
  - github: NorfairKing/validity
    commit: 466bb2f140e62cae0d4fe3770681c3d74e99cf40
    subdirs:
    - genvalidity
    - genvalidity-aeson
    - genvalidity-bytestring
    - genvalidity-containers
    - genvalidity-criterion
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-hspec-binary
    - genvalidity-hspec-cereal
    - genvalidity-hspec-hashable
    - genvalidity-hspec-optics
    - genvalidity-hspec-persistent
    - genvalidity-path
    - genvalidity-persistent
    - genvalidity-property
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-sydtest-hashable
    - genvalidity-sydtest-lens
    - genvalidity-sydtest-persistent
    - genvalidity-text
    - genvalidity-time
    - genvalidity-unordered-containers
    - genvalidity-uuid
    - genvalidity-vector
    - validity
    - validity-aeson
    - validity-bytestring
    - validity-containers
    - validity-path
    - validity-persistent
    - validity-primitive
    - validity-scientific
    - validity-text
    - validity-time
    - validity-unordered-containers
    - validity-uuid
    - validity-vector
  - github: NorfairKing/safe-coloured-text
    commit: 2e61b50dfa65bed862aff903f574175cfc747e14
    subdirs:
      - safe-coloured-text
      - safe-coloured-text-terminfo
  - github: NorfairKing/sydtest
    commit: aac96e2e520a4fca97bccd3403721dc0036b026f
    subdirs:
      - sydtest
      - sydtest-discover
      - sydtest-process
      - sydtest-typed-process
      - sydtest-wai
      - sydtest-yesod

  - github: NorfairKing/autodocodec
    commit: be340221275c6a26be6afe80548d2b834df0dbcf
    subdirs:
      - autodocodec
      - autodocodec-yaml
      - autodocodec-schema

# When bumping the resolver, update the GHC version in shell.nix accordingly.
resolver: lts-18.20

nix:
  enable: true
  packages: [ zlib consul ]

#nix:
#  shell-file: shell.nix
