flags: {}
packages:
- '.'
extra-deps:
  - envparse-0.4.1@sha256:989902e6368532548f61de1fa245ad2b39176cddd8743b20071af519a709ce30,2842
  - yamlparse-applicative-0.1.0.2@sha256:bda91f2818c1b5b124963931cb7f9a4e5758d026c09713e9ae2234534062747d,2133
  - github: NorfairKing/safe-coloured-text
    commit: 2e61b50dfa65bed862aff903f574175cfc747e14
    subdirs:
      - safe-coloured-text
      - safe-coloured-text-terminfo
  - github: NorfairKing/sydtest
    commit: 83685ec68c3c167503ba8aee44000f2d8bb43a07
    subdirs:
      - sydtest
      - sydtest-discover
      - sydtest-wai
      - sydtest-yesod

# When bumping the resolver, update the GHC version in shell.nix accordingly.
resolver: lts-18.20

nix:
  shell-file: shell.nix
