name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["2.3.1"]
        ghc: ["8.8.3"]

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: actions/setup-haskell@v1.1
      name: Setup Haskell Stack
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Install Consul
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
        sudo apt update
        sudo apt install unzip
        wget -q 'https://releases.hashicorp.com/consul/1.9.0/consul_1.9.0_linux_amd64.zip'
        unzip "consul_1.9.0_linux_amd64.zip"
        sudo mkdir -p ~/.local/bin/ && sudo mv consul ~/.local/bin/ && sudo chmod +x ~/.local/bin/consul
        
    - name: Build
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
        PATH=~/.local/bin/:$PATH stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
        PATH=~/.local/bin/:$PATH stack test --system-ghc
